#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J plinkClean
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 16
#BSUB -W 0:08
#BSUB -R rusage[mem=40000]
#BSUB -o /sc/orga/projects/EPIASD/splicingQTL/lsf_output/cleanVCF_postLDQC_%J_output.txt

module load plink/1.90
ml bcftools
ml vcftools

vcfPath='/sc/orga/projects/EPIASD/splicingQTL/intermediate_files/geno/'
vcfFile='Capstone4.sel.idsync.2allele.maf5.mind1.geno1.hwe1e-5.highLDexcl.indep1500_150_.2'

plink --vcf ${vcfPath}${vcfFile}.vcf --double-id --biallelic-only --maf 0.05 --mind 0.01 --geno 0.01 --out ${vcfPath}${vcfFile}.postQCcleanup --recode vcf-iid
