#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J plinkPCA
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 16
#BSUB -W 0:20
#BSUB -R rusage[mem=40000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/plinkPCA_%J_output.txt

module load plink/1.90
ml bcftools
ml vcftools

vcfdir=/sc/arion/scratch/belmoj01/splicingQTL/
vcffile=Capstone4.sel.hasPhenosOnly.idsync.2allele.maf01.mind05.geno05.hwe1e-6.deduped
outdir=/sc/arion/projects/EPIASD/splicingQTL/output/geno_wasp/geno_pca_res/${vcffile}--thin-count200000/

mkdir -p $outdir

plink --vcf $vcfdir/$vcffile.vcf --double-id --thin-count 200000 --pca header --out $outdir/$vcffile
