#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J runVarPt
#BSUB -P acc_pintod02b
#BSUB -m bashia02
#BSUB -q private
#BSUB -n 21
#BSUB -W 5:00
#BSUB -R rusage[mem=28400]
#BSUB -o /sc/orga/projects/EPIASD/splicingQTL/lsf_output/runVarPt%J_output.txt

resultsDir='results/091319_noncorCovars+10HCPs_lambda20.20.20'

module load R

Rscript /sc/orga/projects/EPIASD/splicingQTL/varPart/check_covars_varPt.R
mv varPart ${resultsDir}
mv varpart_* ${resultsDir}
mv .Rdata ${resultsDir}
