#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J annotate_egenes
#BSUB -P acc_pintod02b
#BSUB -q premium
#BSUB -n 1
#BSUB -W 0:10
#BSUB -R rusage[mem=12000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/annotate_eGenes_output_%J.txt

fqtlBedDir=/sc/arion/projects/EPIASD/splicingQTL/intermediate_files/pheno_wasp/
fqtlBedFile=Phenotype.bed

idmapfile=/sc/arion/projects/EPIASD/splicingQTL/analysis/annotationBEDs/gencodeV19/gencode_ENSG_to_ENST.txt

annotBedDir=/sc/arion/projects/EPIASD/splicingQTL/analysis/annotationBEDs/gencodeV19/newBed_0904020/
annotBedFile=gencode.v19.annotation.bed

outFile=intron-gene_annotations.txt

ml bedtools
ml python/3.7.3

# -wo flag writes matching rows from both files & all columns
# -wb flag writes ONLY the rows that overlap from the ENSEMBL genes .BED file
bedtools intersect -wo -a $fqtlBedDir$fqtlBedFile -b $annotBedDir$annotBedFile > $fqtlBedDir$outFile

# Read the output file & report the number of unique gene IDs
echo "python3 count_eGenes_allPhenos.py $fqtlBedDir$outFile $idmapfile $fqtlBedDir$fqtlResFile"
python3 count_eGenes_allPhenos.py $fqtlBedDir$outFile $idmapfile $fqtlBedDir$fqtlBedFile
