#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J annotate_egenes
#BSUB -P acc_pintod02b
#BSUB -q premium
#BSUB -n 1
#BSUB -W 0:10
#BSUB -R rusage[mem=12000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/annotate_eGenes_output_%J.txt

fqtldir=$1 # sQTL results dir
fqtlbed=$2 # bed file of feature to overlap
fqtlres=$3 # sQTL results summary

feattype=$4 # {'pid','sid'} type of feature contained in $fqtlbed

annotdir=$5 # GENCODE annotation dir
annotbed=$6 # bed file of GENCODE transcripts

outfile=${feattype}-gene_annotations.txt # Name of overlap file produced by bedtools

pydir=/sc/arion/projects/EPIASD/splicingQTL/scripts/post_fastQTL_wrapup_GTEx/addQTLgenes # Directory containing the count_eGenes.py script

ml bedtools
ml python/3.7.3

# -wo flag writes matching rows from both files & all columns
# -wb flag writes ONLY the rows that overlap from the gene model .BED file
bedtools intersect -wo -s -f 1.0 -a $fqtldir/$fqtlbed -b $annotdir/$annotbed > $fqtldir/$outfile

# Read the output file & report the number of unique gene IDs
echo "python3 $pydir/count_eGenes.py $fqtldir/$outfile $fqtldir/$fqtlres $feattype --tag _jmb"
python3 $pydir/count_eGenes.py $fqtldir/$outfile $fqtldir/$fqtlres $feattype --tag _jmb
