#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J leafcutting
#BSUB -P acc_pintod02b
#BSUB -q normal
#BSUB -n 16
#BSUB -W 03:00
#BSUB -R rusage[mem=24000]
#BSUB -o /sc/orga/projects/EPIASD/splicingQTL/lsf_output/%J_output.txt

# See reference here: http://davidaknowles.github.io/leafcutter/articles/sQTL.html
module load python/3.7.3
module load leafcutter
#countsPath='/sc/orga/scratch/belmoj01/phenoworkdir/out-extra3-100kb-covar_clusters_ilen100kb_reads50_ratio0.01_perind_numers.counts.idsync.gz' #Counts
#countsPath='/sc/orga/work/belmoj01/sqtl/rename_workdir/out-extra3-100kb-covar_clusters_ilen100kb_reads50_ratio0.01_perind.counts.idsync.gz' #Ratios
countsPath='/sc/orga/projects/EPIASD/splicingQTL/intermediate_files/pheno/out-extra3-100kb-covar_clusters_ilen100kb_reads50_ratio0.01_perind.counts.idsync.deduped.gz' #Ratios
python /hpc/packages/minerva-common/leafcutter/1.0/leafcutter/scripts/prepare_phenotype_table.py ${countsPath} -p 20
