#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J runVarPt
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 21
#BSUB -W 6:00
#BSUB -R rusage[mem=75000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/runVarPt_minCovars_%J_output.txt

resultsDir=/sc/arion/projects/EPIASD/splicingQTL/output/varPart/leafcutter_analysis1

module load R

mkdir -p $resultsDir

Rscript /sc/arion/projects/EPIASD/splicingQTL/scripts/pre_fastQTL/varPart/check_covars_varPt_minCovars.R
mv varPart $resultsDir
mv varpart_* $resultsDir
mv .Rdata $resultsDir
