#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J runVarPt
#BSUB -P acc_pintod02b
#BSUB -q premium
#BSUB -n 26
#BSUB -W 8:00
#BSUB -R rusage[mem=140000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/runVarPt%J_output.txt

resultsDir=results/092120_allCovars+20genoPCs_lambda1.1.1

module load R

mkdir -p $resultsDir

Rscript /sc/arion/projects/EPIASD/splicingQTL/varPart/check_covars_varPt.R

mv varPart $resultsDir
mv varpart_* $resultsDir
mv .RData $resultsDir
