#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J leafcutting
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 16
#BSUB -W 01:00
#BSUB -R rusage[mem=50000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/%J_output.txt

# See reference here: http://davidaknowles.github.io/leafcutter/articles/sQTL.html
ml python/3.7.3
ml leafcutter

countsPath=/sc/arion/scratch/belmoj01/splicingQTL/out-extra3-100kb-covar_clusters_ilen100kb_reads50_ratio0.01_perind.counts.idsync.deduped.gz #Ratios

python /hpc/packages/minerva-common/leafcutter/1.0/leafcutter/scripts/prepare_phenotype_table.py ${countsPath} -p 20
