#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J plinkRemoveLinkedSNPs
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 1
#BSUB -W 01:30
#BSUB -R rusage[mem=130000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/remove_LD_SNPs_%J_output.txt

# Given a list of sSNPs, extract these SNPs from the subset of EUR 1KG SNPs. Then, filter out the SNPs in high LD (r2 > 0.8), and return the remaining SNPs that can be used as input to GREGOR.
# NOTE: The reference used here and file rsid2chrpos.map are prepared by prepare_1kg_EUR_ref.lsf 

module load plink/1.90

LDwindow=1500
LDstep=150
LDthresh=0.8

inSNPsdir=/sc/arion/projects/EPIASD/splicingQTL/intermediate_files/fqtl_output_wasp/20genoPCs_nogenoInHCP/deduped_mincovars+seqPC9_15HCPs/
#inSNPsdir=/sc/arion/projects/EPIASD/splicingQTL/analysis/annotationBEDs/Walker2018_data/
inSNPsfile=uniqueLeadSNPuniquephenos-chrpos.txt

tmpdir=/sc/arion/scratch/belmoj01/GREGOR/tmp/
refname=all_phase3.EUR.dedupe

##################################################

# Make 3 col BED file of coordinates 
sort ${inSNPsdir}${inSNPsfile} | uniq | gawk 'BEGIN{FS="\t"}; {match($1,"([0-9XYM]+):([0-9]+)", coords); print coords[1],coords[2],coords[2],coords[1]":"coords[2]}' > ${inSNPsdir}${inSNPsfile}.extract.in

# Filter by SNP coords to keep only QTL SNPs.Then, calculate LD & produce list of unlinked SNPs   
plink --bfile ${tmpdir}$refname.EUR.dedupe \
      --allow-extra-chr \
      --update-name ${tmpdir}rsid2chrpos.map \
      --extract range ${inSNPsdir}${inSNPsfile}.extract.in \
      --indep-pairwise ${LDwindow} ${LDstep} ${LDthresh}
mv plink.prune.in ${inSNPsdir}uniqueLeadSNPuniquephenos-chrpos-LD${LDthresh}.txt_noChr
sed 's/^/chr/g' ${inSNPsdir}uniqueLeadSNPuniquephenos-chrpos-LD${LDthresh}.txt_noChr > ${inSNPsdir}uniqueLeadSNPuniquephenos-chrpos-LD${LDthresh}.txt

# Remove stray plink files
rm plink*
