#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J makeSignificantCluterBed
#BSUB -P acc_pintod02b
#BSUB -q express
##BSUB -m bashia02
##BSUB -q private
#BSUB -n 1
#BSUB -W 0:10
#BSUB -R rusage[mem=12000]
#BSUB -o /sc/orga/projects/EPIASD/splicingQTL/lsf_output/makeSigClustBed_%J_output.txt

ml python/3.7.3

fqtlResDir='/sc/orga/projects/EPIASD/splicingQTL/intermediate_files/fqtl_output/20genoPCs_nogeno/deduped_mincovars_40HCPs/'
fqtlResFile='significant_sqtl.csv'

phenoBedDir='/sc/orga/projects/EPIASD/splicingQTL/intermediate_files/pheno/'
phenoBedFile='Phenotype.bed'

# Print cluster ID and pipe it to grep to extract the relevant rows from the complete phenotype .BED file -- NOT USED
#awk {'print $1'} ${fqtlResDir}${fqtlResFile} | grep -f - ${phenoBedDir}${phenoBedFile} > ${fqtlResDir}significant_clusters.bed

python3 make_significant_bed.py ${phenoBedDir}${phenoBedFile} ${fqtlResDir}${fqtlResFile}
