#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J plinkClean
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 16
#BSUB -W 0:12
#BSUB -R rusage[mem=40000]
#BSUB -o /sc/orga/projects/EPIASD/splicingQTL/lsf_output/cleanVCF_QC_%J_output.txt

module load plink/1.90
ml bcftools
ml vcftools

vcfdir=/sc/arion/scratch/belmoj01/splicingQTL/
vcffile=Capstone4.sel.hasPhenosOnly.idsync.vcf
vcfoutdir=/sc/arion/scratch/belmoj01/splicingQTL/
vcfQCedfile=Capstone4.sel.hasPhenosOnly.idsync.2allele.maf01.mind05.geno05

mkdir -p $vcfoutdir

plink --vcf $vcfdir/$vcffile --double-id --biallelic-only --maf 0.01 --mind 0.05 --geno 0.05 --out $vcfoutdir/$vcfQCedfile --recode vcf-iid
