#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J plinkClean
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 16
#BSUB -W 0:10
#BSUB -R rusage[mem=40000]
#BSUB -o /sc/arion/projects/EPIASD/splicingQTL/lsf_output/cleanVCF_HWE_%J_output.txt

module load plink/1.90
module load python/3.7.3

vcfdir=/sc/arion/scratch/belmoj01/splicingQTL/
vcffile=Capstone4.sel.hasPhenosOnly.idsync.2allele.maf01.mind05.geno05
ctlonlymetadata=/sc/arion/projects/EPIASD/splicingQTL/data/metadata/subsets/meta_matchedIDs_CTLonly.csv
vcfHWEoutfile=${vcffile}.hwe1e-6

# Get HWE pvals for Control samples only
plink --vcf $vcfdir/$vcffile.vcf --double-id --keep-fam $ctlonlymetadata --hardy -out HWEpvals
# Make file of IDs to exclude based on HWE pval
python3 makeHWEexclude.py HWEpvals.hwe 0.000001
# Drop variants in ALL samples that are not in HWE
plink --vcf $vcfdir/$vcffile.vcf --double-id --exclude hwe_excludes.out --out $vcfdir/$vcfHWEoutfile --recode vcf-iid

