#!/bin/bash
# To run: bsub [options] < this_scripts_name
#BSUB -J plinkClean
#BSUB -P acc_pintod02b
#BSUB -q express
#BSUB -n 16
#BSUB -W 00:10
#BSUB -R rusage[mem=40000]
#BSUB -o /sc/orga/projects/EPIASD/splicingQTL/lsf_output/cleanVCF_LD_%J_output.txt

module load plink/1.90
ml bcftools
ml vcftools

vcfPath=/sc/arion/scratch/belmoj01/splicingQTL/
vcfFile=Capstone4.sel.hasPhenosOnly.idsync.2allele.maf01.mind05.geno05.hwe1e-6.deduped
vcfLDOutFile=${vcfFile}.highLDexcl.indep1500_150_0.2
highldfile=/sc/arion/projects/pintod02c/reference-databases/high_LD_regions/high_ld_and_autsomal_regions_hg19.txt

plink --vcf ${vcfPath}${vcfFile}.vcf --double-id --indep-pairwise 1500 150 0.2
plink --vcf ${vcfPath}${vcfFile}.vcf --double-id --extract plink.prune.in --exclude range $highldfile --out ${vcfPath}${vcfLDOutFile} --recode vcf-iid


